apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-actions-runner-controller-leader-election
  namespace: git-action-runner-new
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-actions-runner-controller-leader-election
  namespace: git-action-runner-new
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-actions-runner-controller-leader-election
subjects:
- kind: ServiceAccount
  name: release-name-actions-runner-controller
  namespace: git-action-runner-new
