apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-actions-runner-controller
  namespace: git-action-runner-new
  labels:
    helm.sh/chart: actions-runner-controller-0.22.0
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.27.0"
    app.kubernetes.io/managed-by: Helm
